
TRAINING_PATTERN_LENGTH = 50
TRAINING_EPOCHS = 40
TRAINING_BATCH_SIZE = 16
HIDDEN_LAYER_SIZE_MULTIPLIER = 2
DROPOUT = 0.2
ACTIVATION_FUNC = "sigmoid"
LOSS_FUNC = "categorical_crossentropy"
OPTIMIZER = "rmsprop"

TEST_STARTING_INDEX = 0
TEST_PATTERN_LENGTH = 400
NOTE_OFFSET = 0.5

GPUS = 1
CPUS = 6
USE_GPU = True

DATASET_PATH = "midi_songs/**/*.mid"
OUTPUT_PATH = "output/output.mid"
